build:
    maxIssues: 0
    excludeCorrectable: false
    weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
    validation: true
    excludes: ''

processors:
    active: true
    exclude:
        - 'DetektProgressListener'

console-reports:
    active: true
    exclude:
        - 'ProjectStatisticsReport'
        - 'ComplexityReport'
        - 'NotificationReport'

output-reports:
    active: true
    exclude:
    # - 'TxtOutputReport'
    # - 'XmlOutputReport'
    # - 'HtmlOutputReport'

comments:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    EndOfSentenceFormat:
        active: false
        endOfSentenceFormat: '([.?!][ \t\n\r\f<])|([.?!:]$)'
    UndocumentedPublicClass:
        active: false
        searchInNestedClass: true
        searchInInnerClass: true
        searchInInnerObject: true
        searchInInnerInterface: true
    UndocumentedPublicFunction:
        active: false
    UndocumentedPublicProperty:
        active: false

complexity:
    active: true
    ComplexCondition:
        active: true
        threshold: 4
    ComplexMethod:
        active: true
        threshold: 15
        ignoreSingleWhenExpression: false
        ignoreSimpleWhenEntries: false
        ignoreNestingFunctions: false
        nestingFunctions: [run, let, apply, with, also, use, forEach, isNotNull, ifNull]
    LargeClass:
        active: true
        threshold: 600
    LongMethod:
        active: true
        threshold: 60
    LongParameterList:
        active: true
        functionThreshold: 6
        constructorThreshold: 7
        ignoreDefaultParameters: false
        ignoreDataClasses: true
        ignoreAnnotated: []
    NestedBlockDepth:
        active: true
        threshold: 4
    StringLiteralDuplication:
        active: false
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        threshold: 3
        ignoreAnnotation: true
        excludeStringsWithLessThan5Characters: true
        ignoreStringsRegex: '$^'
    TooManyFunctions:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        thresholdInFiles: 11
        thresholdInClasses: 11
        thresholdInInterfaces: 11
        thresholdInObjects: 11
        thresholdInEnums: 11
        ignoreDeprecated: false
        ignorePrivate: false
        ignoreOverridden: false

coroutines:
    active: true
    GlobalCoroutineUsage:
        active: false
    RedundantSuspendModifier:
        active: false

empty-blocks:
    active: true
    EmptyCatchBlock:
        active: true
        allowedExceptionNameRegex: '_|(ignore|expected).*'
    EmptyClassBlock:
        active: true
    EmptyDefaultConstructor:
        active: true
    EmptyDoWhileBlock:
        active: true
    EmptyElseBlock:
        active: true
    EmptyFinallyBlock:
        active: true
    EmptyForBlock:
        active: true
    EmptyFunctionBlock:
        active: true
        ignoreOverridden: false
    EmptyIfBlock:
        active: true
    EmptyInitBlock:
        active: true
    EmptyKtFile:
        active: true
    EmptySecondaryConstructor:
        active: true
    EmptyTryBlock:
        active: true
    EmptyWhenBlock:
        active: true
    EmptyWhileBlock:
        active: true

exceptions:
    active: true
    ExceptionRaisedInUnexpectedLocation:
        active: false
        methodNames: [toString, hashCode, equals, finalize]
    NotImplementedDeclaration:
        active: false
    PrintStackTrace:
        active: false
    RethrowCaughtException:
        active: false
    ReturnFromFinally:
        active: false
        ignoreLabeled: false
    SwallowedException:
        active: false
        ignoredExceptionTypes:
            - InterruptedException
            - NumberFormatException
            - ParseException
            - MalformedURLException
        allowedExceptionNameRegex: '_|(ignore|expected).*'
    ThrowingExceptionFromFinally:
        active: false
    ThrowingExceptionInMain:
        active: false
    ThrowingExceptionsWithoutMessageOrCause:
        active: false
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        exceptions:
            - IllegalArgumentException
            - IllegalStateException
            - IOException
    ThrowingNewInstanceOfSameException:
        active: false
    TooGenericExceptionCaught:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        exceptionNames:
            - ArrayIndexOutOfBoundsException
            - Error
            - Exception
            - IllegalMonitorStateException
            - NullPointerException
            - IndexOutOfBoundsException
            - RuntimeException
            - Throwable
        allowedExceptionNameRegex: '_|(ignore|expected).*'
    TooGenericExceptionThrown:
        active: true
        exceptionNames:
            - Error
            - Exception
            - Throwable
            - RuntimeException

formatting:
    active: true
    android: false
    autoCorrect: true
    AnnotationOnSeparateLine:
        active: false
        autoCorrect: true
    ChainWrapping:
        active: true
        autoCorrect: true
    CommentSpacing:
        active: true
        autoCorrect: true
    EnumEntryNameCase:
        active: false
        autoCorrect: true
    Filename:
        active: true
    FinalNewline:
        active: true
        autoCorrect: true
        insertFinalNewLine: true
    ImportOrdering:
        active: false
        autoCorrect: true
        layout: 'idea'
    Indentation:
        active: false
        autoCorrect: true
        indentSize: 4
        continuationIndentSize: 4
    MaximumLineLength:
        active: true
        maxLineLength: 120
    ModifierOrdering:
        active: true
        autoCorrect: true
    MultiLineIfElse:
        active: true
        autoCorrect: true
    NoBlankLineBeforeRbrace:
        active: true
        autoCorrect: true
    NoConsecutiveBlankLines:
        active: true
        autoCorrect: true
    NoEmptyClassBody:
        active: true
        autoCorrect: true
    NoEmptyFirstLineInMethodBlock:
        active: false
        autoCorrect: true
    NoLineBreakAfterElse:
        active: true
        autoCorrect: true
    NoLineBreakBeforeAssignment:
        active: true
        autoCorrect: true
    NoMultipleSpaces:
        active: true
        autoCorrect: true
    NoSemicolons:
        active: true
        autoCorrect: true
    NoTrailingSpaces:
        active: true
        autoCorrect: true
    NoUnitReturn:
        active: true
        autoCorrect: true
    NoUnusedImports:
        active: true
        autoCorrect: true
    NoWildcardImports:
        active: true
    PackageName:
        active: true
        autoCorrect: true
    ParameterListWrapping:
        active: true
        autoCorrect: true
        indentSize: 4
    SpacingAroundColon:
        active: true
        autoCorrect: true
    SpacingAroundComma:
        active: true
        autoCorrect: true
    SpacingAroundCurly:
        active: true
        autoCorrect: true
    SpacingAroundDot:
        active: true
        autoCorrect: true
    SpacingAroundDoubleColon:
        active: false
        autoCorrect: true
    SpacingAroundKeyword:
        active: true
        autoCorrect: true
    SpacingAroundOperators:
        active: true
        autoCorrect: true
    SpacingAroundParens:
        active: true
        autoCorrect: true
    SpacingAroundRangeOperator:
        active: true
        autoCorrect: true
    SpacingBetweenDeclarationsWithAnnotations:
        active: false
        autoCorrect: true
    SpacingBetweenDeclarationsWithComments:
        active: false
        autoCorrect: true
    StringTemplate:
        active: true
        autoCorrect: true

naming:
    active: true
    ClassNaming:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        classPattern: '[A-Z][a-zA-Z0-9]*'
    ConstructorParameterNaming:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        parameterPattern: '[a-z][A-Za-z0-9]*'
        privateParameterPattern: '[a-z][A-Za-z0-9]*'
        excludeClassPattern: '$^'
        ignoreOverridden: true
    EnumNaming:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        enumEntryPattern: '[A-Z][_a-zA-Z0-9]*'
    FunctionNaming:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        functionPattern: '([a-z][a-zA-Z0-9]*)|(`.*`)'
        excludeClassPattern: '$^'
        ignoreOverridden: true
        ignoreAnnotated: ['Composable']
    FunctionParameterNaming:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        parameterPattern: '[a-z][A-Za-z0-9]*'
        excludeClassPattern: '$^'
        ignoreOverridden: true
    ObjectPropertyNaming:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        constantPattern: '[A-Za-z][_A-Za-z0-9]*'
        propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
        privatePropertyPattern: '(_)?[A-Za-z][_A-Za-z0-9]*'
    PackageNaming:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'
    TopLevelPropertyNaming:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        constantPattern: '[A-Z][_A-Z0-9]*'
        propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
        privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'
    VariableNaming:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        variablePattern: '[a-z][A-Za-z0-9]*'
        privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
        excludeClassPattern: '$^'
        ignoreOverridden: true

performance:
    active: true
    ArrayPrimitive:
        active: true
    ForEachOnRange:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    SpreadOperator:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    UnnecessaryTemporaryInstantiation:
        active: true

potential-bugs:
    active: true
    DuplicateCaseInWhenExpression:
        active: true
    EqualsAlwaysReturnsTrueOrFalse:
        active: true
    EqualsWithHashCodeExist:
        active: true
    ExplicitGarbageCollectionCall:
        active: true
    IgnoredReturnValue:
        active: false
        restrictToConfig: true
        returnValueAnnotations: ['*.CheckReturnValue', '*.CheckResult']
    InvalidRange:
        active: true
    IteratorHasNextCallsNextMethod:
        active: true
    IteratorNotThrowingNoSuchElementException:
        active: true
    LateinitUsage:
        active: false
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        ignoreAnnotated: []
        ignoreOnClassesPattern: ''
    MissingWhenCase:
        active: true
    RedundantElseInWhen:
        active: true
    UnreachableCode:
        active: true
    UnsafeCallOnNullableType:
        active: true
    WrongEqualsTypeParameter:
        active: true

style:
    active: true
    CollapsibleIfStatements:
        active: false
    DataClassContainsFunctions:
        active: false
        conversionFunctionPrefix: ['to', 'as']
    EqualsNullCall:
        active: true
    ForbiddenComment:
        active: true
        comments: ['TODO:', 'FIXME:', 'STOPSHIP:']
    FunctionOnlyReturningConstant:
        active: true
        ignoreOverridableFunction: true
        excludedFunctions: ['describeContents']
        ignoreAnnotated: ['dagger.Provides']
    LoopWithTooManyJumpStatements:
        active: true
        maxJumpCount: 1
    MagicNumber:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        ignoreNumbers: ['-1', '0', '1', '2']
        ignoreHashCodeFunction: true
        ignorePropertyDeclaration: false
        ignoreLocalVariableDeclaration: false
        ignoreConstantDeclaration: true
        ignoreCompanionObjectPropertyDeclaration: true
        ignoreAnnotation: false
        ignoreNamedArgument: true
        ignoreEnums: false
        ignoreRanges: false
    MaxLineLength:
        active: true
        maxLineLength: 120
        excludePackageStatements: true
        excludeImportStatements: true
        excludeCommentStatements: false
    MayBeConst:
        active: true
    ModifierOrder:
        active: true
    NewLineAtEndOfFile:
        active: true
    OptionalAbstractKeyword:
        active: true
    ProtectedMemberInFinalClass:
        active: true
    ReturnCount:
        active: true
        max: 2
        excludedFunctions: ['equals']
        excludeLabeled: false
        excludeReturnFromLambda: true
        excludeGuardClauses: false
    SafeCast:
        active: true
    ThrowsCount:
        active: true
        max: 2
    UnnecessaryAbstractClass:
        active: true
        ignoreAnnotated: ['dagger.Module']
    UnnecessaryInheritance:
        active: true
    UnusedPrivateClass:
        active: true
    WildcardImport:
        active: true
        excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
        excludeImports: ['java.util.*', 'kotlinx.android.synthetic.*']
