name: Kotlin CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Firebase config
        run: echo "${{ secrets.FIREBASE_CONFIG }}" > app/src/google-services.json

      - name: Build debug
        run: ./gradlew assembleDebug

  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout static code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: "17"
            distribution: "temurin"

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
        with:
            reviewdog_version: latest

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
            path: ~/.gradle/caches
            key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
            restore-keys: |
                gradle-caches-${{ runner.os }}-

      - name: Grant execute permissions for Ktlint and Detekt
        run: chmod +x ./ktlint.sh ./detekt.sh

      - name: Ktlint Check
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./ktlint.sh

      - name: Detekt Check
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./detekt.sh
